<h1> Hello World no Magento </h1>
<table style="border: 1px solid black;">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nome</th>
            <th>SKU</th>
            <th>Peso</th>
            <th>Preço</th>
            <th>Descrição</th>
        </tr>
    </thead>
    <tbody>
    <?php
        $productCollection = $block->getProductCollection();
        foreach ($productCollection as $product) {
            echo "
            <tr style='border: 1px solid black;'>
                <td>{$product['entity_id']}</td>
                <td>{$product['meta_title']}</td>
                <td>{$product['sku']}</td>
                <td>{$product['weight']}</td>
                <td>{$product['price']}</td>
                <td>{$product['meta_description']}</td>
            </tr>
            ";
        }
    ?>
    </tbody>
</table>

